cursor #dee3e6
cursor_text_color #bfc8cc

foreground            #dee3e6
background            #0f1416
selection_foreground  #1d343b
selection_background  #b3cad4
url_color             #86d1ea

color0   #0f1416
color1   #ff72a1
color2   #75ea81
color3   #fff672
color4   #6cc1de
color5   #17576c
color6   #86d1ea
color7   #e6f2f5
color8   #8c9598
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #a2e7ff
color13  #b2ebff
color14  #cdf2ff
color15  #f8fdff
